### ISSUE TITLE
cloneRangeIfSame in read only subvolume

### ISSUE THREAD

**Issue by miguel-negrao** [redneb/hs-btrfs#1]
When I try to run `cloneRangeIfSame` in files in read only subvolumes created with `btrfs fi sub snapshot -r` I get  `openFd: permission denied (Read-only file system) even` when running the executable as root. Is it possible to make `cloneRangeIfSame` work in read-only snapshots ? In my tests the error comes up on the file in the file list of identical files, and looking at the code I see 

   withFd dstPath WriteOnly $ \fd 

when opening the destination files. Perhaps this should also be `ReadOnly` ?

**Comment by redneb** [comment]
Thanks for report. The problem is that if the file is opened as `ReadOnly`, `cloneRangeIfSame` will not work for non-root users ([here's](https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/fs/read_write.c?h=v4.8#n1744) the relevant check in the kernel). On the other hand, it does seem to work if the user has the `CAP_SYS_ADMIN` capability (e.g. a process with uid 0). So I cannot simply change `WriteOnly` to `ReadOnly`. I'll have to come up with a different solution.

**Comment by miguel-negrao** [comment]
thanks for looking at this. Maybe add a version of the function, or an argument to the function, that makes it open with read only ? As an example duperemove has a [cmd-line switch for that](https://github.com/markfasheh/duperemove/blob/master/duperemove.c#L396).

**Comment by redneb** [comment]
I just pushed a new branch called `check-capabilities` that includes a workaround for this issue. The idea is to detect if the process has the `CAP_SYS_ADMIN` capability and choose between `ReadOnly` and `WriteOnly` based on that. This should make `cloneRangeIfSame` work for both unprivileged and privileged users on read-write subvolumes, while also supporting read-only subvolumes for privileged users. I have tested it and it works, but can you try that branch too before I publish a new version on hackage?

**Comment by miguel-negrao** [comment]
Tried your new branch, seems to work fine in my system. I can dedupe on read only snapshots. Thanks !

**Comment by redneb** [comment]
0.1.2.1 in available on hackage and it includes the fix.
